name: Deploy only on main branch
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  #  only runs on main branch
    steps:
      - name: Deploying...
        run: echo "Deploying to production..."
