name: Dependent Multi Jobs workflow
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    
jobs:
  first-workflow-jobs: 
    runs-on: ubuntu-latest

    steps:
      - name: First workflow jobs step
        run: |
          echo "Hello, first workflow"

  second-workflow-jobs:
    runs-on: ubuntu-latest

    needs: [first-workflow-jobs]

    steps:
      - name: Second workflow jobs 
        run: |
          echo "Hello, Second workflow"

  third-workflow-jobs:
    runs-on: ubuntu-latest

    needs: [first-workflow-jobs, second-workflow-jobs]

    steps:
      - name: third workflow jobs 
        run: |
          echo "Hello, third workflow"