name: Value pass workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Mr.X'

jobs:
  get-value-workflow-job:
    runs-on: ubuntu-latest
    outputs:
      greeting-message: ${{ steps.generate_msg.outputs.msg }}  

    steps:
      - name: Generate greetings msg 
        id: generate_msg
        run: |
          echo "msg=Hello, ${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT  

  print-value-workflow-job:
    runs-on: ubuntu-latest
    needs: [get-value-workflow-job]

    steps:
      - name: Print Greetings Message
        run: |
          echo "${{ needs.get-value-workflow-job.outputs.greeting-message }}" 
